
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxwdmmqygbxetsothxkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4d2RtbXF5Z2J4ZXRzb3RoeGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTQ1NzUsImV4cCI6MjA2NDE3MDU3NX0.kgXm9GDDQubhyOHOjTYBNJAYcqOgZR7IOUn6Ivzx--s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Test connection on initialization
console.log('Supabase client initialized with URL:', SUPABASE_URL);
console.log('Supabase client ready:', !!supabase);
